CREATE SEQUENCE SEQ_MATCHING;

CREATE TABLE TBL_MATCHING(
    ID NUMBER CONSTRAINT PK_MATCHING PRIMARY KEY,
    TEAM_ID NUMBER,
    PLACE_ID NUMBER,
    CREATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
    STATS NUMBER DEFAULT 0, --0은 매칭중 , 1은 매칭완료
    CONSTRAINT FK_MATCHING_TEAM FOREIGN KEY(TEAM_ID)
    REFERENCES TBL_TEAM(ID),
    CONSTRAINT FK_MATCHING_PLACE FOREIGN KEY(PLACE_ID)
    REFERENCES TBL_PLACE(ID)
);

SELECT *FROM TBL_MATCHING;