CREATE SEQUENCE SEQ_TEAM;

CREATE TABLE TBL_TEAM(
    ID NUMBER CONSTRAINT PK_TEAM PRIMARY KEY,
    TEAM_NAME VARCHAR2(255) NOT NULL,
    TEAM_MEMBER_NUMBER NUMBER NOT NULL,
    TEAM_MASTER VARCHAR2(255) NOT NULL
);

SELECT * FROM TBL_TEAM;