CREATE SEQUENCE SEQ_REPLY;

CREATE TABLE TBL_REPLY (
   ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
   POST_ID NUMBER NOT NULL,
   MEMBER_ID  NUMBER NOT NULL,
   REPLY_CONTENT VARCHAR2(255) NOT NULL,
   GROUP_ID NUMBER,    -- 그룹 ID (댓글은 NULL, 대댓글은 해당 댓글의 ID)
   REPLY_DEPTH NUMBER DEFAULT 0, -- 댓글은 0, 대댓글은 1 이상
   CREATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
   UPDATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT FK_REPLY_POST FOREIGN KEY (POST_ID)
   REFERENCES TBL_POST(ID),
   CONSTRAINT FK_REPLY_MEMBER FOREIGN KEY (MEMBER_ID)
   REFERENCES TBL_MEMBER(ID),
   CONSTRAINT FK_REPLY_GROUP FOREIGN KEY (GROUP_ID)
   REFERENCES TBL_REPLY(ID) ON DELETE CASCADE -- 부모요소 사라지면 자식요소도 사라짐
    -- 자기 자신을 참조하는 외래키
);

DROP TABLE TBL_REPLY;

SELECT * FROM TBL_REPLY;

