CREATE SEQUENCE SEQ_MARKET;

CREATE TABLE TBL_MARKET(
   ID NUMBER CONSTRAINT PK_MARKET PRIMARY KEY,
   MARKET_NAME VARCHAR2(255) NOT NULL,
   PRODUCT_NAME VARCHAR2(255) NOT NULL,
   PRODUCT_NUMBER VARCHAR2(255) NOT NULL
);

SELECT * FROM TBL_MARKET;
