CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
    ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
    MEMBER_EMAIL VARCHAR2(255),
    MEMBER_PASSWORD VARCHAR2(255),
    MEMBER_KAKAO_EMAIL VARCHAR2(255),
    MEMBER_KAKAO_PROFILE_URL VARCHAR2(255),
    MEMBER_NAME VARCHAR2(255),
    MEMBER_STATUS NUMBER DEFAULT 1,
    MEMBER_LOGIN_TYPE VARCHAR2(255) DEFAULT 'MEMBER',
    UPDATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
    CREATED_DATE DATE DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM TBL_MEMBER;



DROP TABLE TBL_MEMBER;

DROP SEQUENCE SEQ_MEMBER;